using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Rat.Research.Minigame;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Rat.Research.Minigame;

[GenerateTypedNameReferences]
public sealed partial class RatResearchMinigameMenu : FancyWindow
{
    private readonly List<int> _sequenceAnswer = new();
    private readonly List<int> _memoryAnswer = new();
    private readonly List<SpinBox> _wireSpins = new();
    private readonly List<Button> _memoryButtons = new();
    private readonly List<Button> _bitButtons = new();
    private readonly Button[] _waveNoiseButtons;
    private readonly Button[] _cipherShiftButtons;
    private readonly IGameTiming _timing;

    private bool _waveformPopulated;
    private bool _memoryReveal;
    private double _memoryRevealStart;
    private bool _wireBuilt;
    private bool _memoryBuilt;
    private bool _bitBuilt;
    private int _bitMask;
    private int _puzzleSeed;
    private int _lastStage = -1;
    private RatResearchMinigameType _lastType;
    private readonly List<int> _waveformIndexMap = new();
    private readonly int[] _cipherShiftValues = new int[3];
    private List<string> _waveformOptions = new();

    public event Action? OnStartTune;
    public event Action? OnStartSequence;
    public event Action? OnStartPhase;
    public event Action? OnStartHarmonic;
    public event Action? OnStartWaveform;
    public event Action? OnStartCipher;
    public event Action? OnStartTiming;
    public event Action? OnStartWire;
    public event Action? OnStartMemory;
    public event Action? OnStartBitRepair;
    public event Action<int>? OnSubmitTuneBand;
    public event Action<int, int, int>? OnSubmitTune;
    public event Action<int, int, int>? OnSubmitTuneFinalize;
    public event Action<List<int>>? OnSubmitSequence;
    public event Action<int, int>? OnSubmitPhase;
    public event Action<int, int>? OnSubmitHarmonic;
    public event Action<List<int>>? OnSubmitWaveformFilter;
    public event Action<int>? OnSubmitWaveform;
    public event Action<int>? OnSubmitCipherShift;
    public event Action<int>? OnSubmitCipher;
    public event Action<int>? OnSubmitTiming;
    public event Action<int>? OnSubmitWirePort;
    public event Action<List<int>>? OnSubmitWire;
    public event Action<List<int>>? OnSubmitMemory;
    public event Action<int>? OnSubmitBitCount;
    public event Action<int>? OnSubmitBitRepair;

    public RatResearchMinigameMenu()
    {
        RobustXamlLoader.Load(this);
        _timing = IoCManager.Resolve<IGameTiming>();

        _waveNoiseButtons = new[] { WaveNoise0, WaveNoise1, WaveNoise2, WaveNoise3 };
        _cipherShiftButtons = new[] { CipherShift0, CipherShift1, CipherShift2 };

        WaveformSpinBox.IsValid = v => v is >= 0 and <= 3;
        WaveformSpinBox.OverrideValue(0);
        WirePortSpinBox.IsValid = v => v is >= 0 and <= 3;
        WirePortSpinBox.OverrideValue(0);
        BitCountSpinBox.IsValid = v => v is >= 0 and <= 8;
        BitCountSpinBox.OverrideValue(0);

        TuneGameButton.OnPressed += _ => OnStartTune?.Invoke();
        SequenceGameButton.OnPressed += _ => OnStartSequence?.Invoke();
        PhaseGameButton.OnPressed += _ => OnStartPhase?.Invoke();
        HarmonicGameButton.OnPressed += _ => OnStartHarmonic?.Invoke();
        WaveformGameButton.OnPressed += _ => OnStartWaveform?.Invoke();
        CipherGameButton.OnPressed += _ => OnStartCipher?.Invoke();
        TimingGameButton.OnPressed += _ => OnStartTiming?.Invoke();
        WireGameButton.OnPressed += _ => OnStartWire?.Invoke();
        MemoryGameButton.OnPressed += _ => OnStartMemory?.Invoke();
        BitRepairGameButton.OnPressed += _ => OnStartBitRepair?.Invoke();

        TuneBandLowButton.OnPressed += _ => OnSubmitTuneBand?.Invoke(0);
        TuneBandMidButton.OnPressed += _ => OnSubmitTuneBand?.Invoke(1);
        TuneBandHighButton.OnPressed += _ => OnSubmitTuneBand?.Invoke(2);

        DialASlider.OnValueChanged += _ => UpdateTuneLabels();
        DialBSlider.OnValueChanged += _ => UpdateTuneLabels();
        DialCSlider.OnValueChanged += _ => UpdateTuneLabels();
        PhaseASlider.OnValueChanged += _ => UpdatePhaseLabels();
        PhaseBSlider.OnValueChanged += _ => UpdatePhaseLabels();
        StabilitySlider.OnValueChanged += _ => UpdateHarmonicLabels();

        SubmitTuneButton.OnPressed += _ => OnSubmitTune?.Invoke(
            (int) DialASlider.Value, (int) DialBSlider.Value, (int) DialCSlider.Value);
        SubmitTuneFinalizeButton.OnPressed += _ => OnSubmitTuneFinalize?.Invoke(
            (int) DialASlider.Value, (int) DialBSlider.Value, (int) DialCSlider.Value);

        SeqColor0.OnPressed += _ => AddSequenceColor(0);
        SeqColor1.OnPressed += _ => AddSequenceColor(1);
        SeqColor2.OnPressed += _ => AddSequenceColor(2);
        SeqColor3.OnPressed += _ => AddSequenceColor(3);
        SequenceResetButton.OnPressed += _ => ResetSequenceAnswer();
        SubmitSequenceButton.OnPressed += _ =>
        {
            if (_sequenceAnswer.Count == 4)
                OnSubmitSequence?.Invoke(new List<int>(_sequenceAnswer));
        };

        SubmitPhaseButton.OnPressed += _ => OnSubmitPhase?.Invoke(
            (int) PhaseASlider.Value, (int) PhaseBSlider.Value);
        SubmitHarmonicButton.OnPressed += _ =>
        {
            var stability = (int) StabilitySlider.Value;
            OnSubmitHarmonic?.Invoke(stability, 100 - stability);
        };

        SubmitWaveformFilterButton.OnPressed += _ =>
        {
            var picks = new List<int>();
            for (var i = 0; i < _waveNoiseButtons.Length; i++)
            {
                if (_waveNoiseButtons[i].Pressed)
                    picks.Add(i);
            }

            OnSubmitWaveformFilter?.Invoke(picks);
        };

        WaveformList.OnItemSelected += args =>
        {
            WaveformSpinBox.OverrideValue(args.ItemIndex);
            WaveformList[args.ItemIndex].Selected = true;
        };
        SubmitWaveformButton.OnPressed += _ =>
        {
            var selected = WaveformList.GetSelected().FirstOrDefault();
            if (selected == null)
                return;

            var listIdx = WaveformList.IndexOf(selected);
            if (listIdx >= 0 && listIdx < _waveformIndexMap.Count)
                OnSubmitWaveform?.Invoke(_waveformIndexMap[listIdx]);
        };

        CipherShift0.OnPressed += _ => OnSubmitCipherShift?.Invoke(_cipherShiftValues[0]);
        CipherShift1.OnPressed += _ => OnSubmitCipherShift?.Invoke(_cipherShiftValues[1]);
        CipherShift2.OnPressed += _ => OnSubmitCipherShift?.Invoke(_cipherShiftValues[2]);
        CipherOption1.OnPressed += _ => OnSubmitCipher?.Invoke(1);
        CipherOption2.OnPressed += _ => OnSubmitCipher?.Invoke(2);
        CipherOption3.OnPressed += _ => OnSubmitCipher?.Invoke(3);

        CatchTimingButton.OnPressed += _ => OnSubmitTiming?.Invoke(GetTimingPosition());
        SubmitWirePortButton.OnPressed += _ => OnSubmitWirePort?.Invoke(WirePortSpinBox.Value);
        SubmitWireButton.OnPressed += _ =>
        {
            var mapping = new List<int>();
            foreach (var spin in _wireSpins)
                mapping.Add(spin.Value);
            OnSubmitWire?.Invoke(mapping);
        };

        MemoryResetButton.OnPressed += _ => ResetMemoryAnswer();
        SubmitMemoryButton.OnPressed += _ =>
        {
            if (_memoryAnswer.Count > 0)
                OnSubmitMemory?.Invoke(new List<int>(_memoryAnswer));
        };

        SubmitBitCountButton.OnPressed += _ => OnSubmitBitCount?.Invoke(BitCountSpinBox.Value);
        SubmitBitRepairButton.OnPressed += _ => OnSubmitBitRepair?.Invoke(RatPuzzleUiHelper.ComputeBitMask(_bitButtons));

        UpdateTuneLabels();
        UpdatePhaseLabels();
        UpdateHarmonicLabels();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        if (TimingPanel.Visible)
            TimingPositionLabel.Text = Loc.GetString("rat-research-minigame-timing-position",
                ("value", GetTimingPosition()));
    }

    public void UpdateState(RatResearchMinigameBuiState state)
    {
        PointsLabel.Text = Loc.GetString("rat-research-minigame-points", ("points", state.ServerPoints));
        GamePickerPanel.Visible = !state.PuzzleActive;
        PuzzlePanel.Visible = true;
        IdlePuzzleLabel.Visible = !state.PuzzleActive;

        HidePuzzlePanels();

        if (!state.PuzzleActive)
        {
            ActiveGameLabel.Text = string.Empty;
            StageLabel.Text = string.Empty;
            HintLabel.Text = Loc.GetString("rat-research-minigame-idle");
            _waveformPopulated = false;
            WaveformList.Clear();
            _wireBuilt = false;
            _memoryBuilt = false;
            _bitBuilt = false;
            _lastStage = -1;
            return;
        }

        ActiveGameLabel.Text = Loc.GetString("rat-research-minigame-active", ("game", GetGameName(state.ActiveType)));
        StageLabel.Text = Loc.GetString("rat-research-minigame-stage",
            ("current", state.PuzzleStage + 1), ("total", state.PuzzleStageCount));
        PuzzleTitleLabel.Text = GetStageTitle(state);

        if (_lastType != state.ActiveType || _lastStage != state.PuzzleStage)
        {
            _sequenceAnswer.Clear();
            ResetSequenceAnswerDisplay();
            _memoryAnswer.Clear();
            _memoryReveal = true;
            _memoryRevealStart = _timing.RealTime.TotalSeconds;
            if (_lastType != state.ActiveType)
            {
                _waveformPopulated = false;
                _wireBuilt = false;
                _memoryBuilt = false;
                _bitBuilt = false;
            }
        }

        _lastType = state.ActiveType;
        _lastStage = state.PuzzleStage;
        _puzzleSeed = state.PuzzleSeed;

        switch (state.ActiveType)
        {
            case RatResearchMinigameType.FrequencyTune:
                UpdateFrequencyTune(state);
                break;
            case RatResearchMinigameType.SequenceMatch:
                UpdateSequence(state);
                break;
            case RatResearchMinigameType.PhaseLock:
                PhasePanel.Visible = true;
                PhaseStageLabel.Text = state.PuzzleStage == 0
                    ? Loc.GetString("rat-research-minigame-phase-stage-sum")
                    : Loc.GetString("rat-research-minigame-phase-stage-delta",
                        ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));
                HintLabel.Text = Loc.GetString("rat-research-minigame-phase-hint",
                    ("low", state.HintLow), ("high", state.HintHigh));
                PhaseSumLabel.Text = Loc.GetString("rat-research-minigame-sum-target",
                    ("low", state.HintLow), ("high", state.HintHigh));
                break;
            case RatResearchMinigameType.HarmonicBalance:
                HarmonicPanel.Visible = true;
                HarmonicStageLabel.Text = state.PuzzleStage == 0
                    ? Loc.GetString("rat-research-minigame-harmonic-stage-stability",
                        ("low", state.HintLow), ("high", state.HintHigh))
                    : Loc.GetString("rat-research-minigame-harmonic-stage-product",
                        ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));
                HintLabel.Text = Loc.GetString("rat-research-minigame-harmonic-hint",
                    ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));
                HarmonicProductLabel.Text = state.PuzzleStage == 0
                    ? Loc.GetString("rat-research-minigame-harmonic-sum")
                    : Loc.GetString("rat-research-minigame-product-target",
                        ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));
                break;
            case RatResearchMinigameType.WaveformPick:
                UpdateWaveform(state);
                break;
            case RatResearchMinigameType.CipherDecrypt:
                UpdateCipher(state);
                break;
            case RatResearchMinigameType.TimingPulse:
                TimingPanel.Visible = true;
                HintLabel.Text = state.PuzzleStage == 0
                    ? Loc.GetString("rat-research-minigame-timing-calibrate")
                    : Loc.GetString("rat-research-minigame-timing-hint");
                TimingHintLabel.Text = state.PuzzleStage == 0
                    ? Loc.GetString("rat-research-minigame-timing-calibrate-hint",
                        ("center", (state.TimingZoneLow + state.TimingZoneHigh) / 2))
                    : Loc.GetString("rat-research-minigame-timing-zone",
                        ("low", state.TimingZoneLow), ("high", state.TimingZoneHigh));
                break;
            case RatResearchMinigameType.WireRouting:
                UpdateWire(state);
                break;
            case RatResearchMinigameType.MemoryGrid:
                MemoryPanel.Visible = true;
                HintLabel.Text = state.PuzzleStage == 0
                    ? Loc.GetString("rat-research-minigame-memory-hint")
                    : Loc.GetString("rat-research-minigame-memory-reverse");
                if (!_memoryBuilt)
                    BuildMemoryGrid();
                UpdateMemoryDisplay(state.MemoryPattern, state.PuzzleStage == 0);
                break;
            case RatResearchMinigameType.BitRepair:
                UpdateBitRepair(state);
                break;
        }
    }

    private void UpdateFrequencyTune(RatResearchMinigameBuiState state)
    {
        switch (state.PuzzleStage)
        {
            case 0:
                TuneBandPanel.Visible = true;
                HintLabel.Text = Loc.GetString("rat-research-minigame-tune-band-hint",
                    ("low", state.HintLow), ("high", state.HintHigh));
                break;
            case 1:
                TunePanel.Visible = true;
                SubmitTuneButton.Visible = true;
                SubmitTuneFinalizeButton.Visible = false;
                TuneModulationLabel.Visible = false;
                HintLabel.Text = Loc.GetString("rat-research-minigame-tune-hint",
                    ("low", state.HintLow), ("high", state.HintHigh));
                break;
            default:
                TunePanel.Visible = true;
                SubmitTuneButton.Visible = false;
                SubmitTuneFinalizeButton.Visible = true;
                TuneModulationLabel.Visible = true;
                TuneModulationLabel.Text = Loc.GetString("rat-research-minigame-tune-modulation",
                    ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));
                HintLabel.Text = Loc.GetString("rat-research-minigame-tune-final-hint");
                break;
        }
    }

    private void UpdateSequence(RatResearchMinigameBuiState state)
    {
        SequencePanel.Visible = true;
        SequenceModeLabel.Text = state.SequenceTransformMode switch
        {
            1 => Loc.GetString("rat-research-minigame-sequence-reverse"),
            2 => Loc.GetString("rat-research-minigame-sequence-rotate"),
            _ => Loc.GetString("rat-research-minigame-sequence-forward"),
        };
        HintLabel.Text = SequenceModeLabel.Text;
        PopulateSequenceTarget(state.Sequence);
    }

    private void UpdateWaveform(RatResearchMinigameBuiState state)
    {
        if (state.PuzzleStage == 0)
        {
            WaveformFilterPanel.Visible = true;
            _waveformOptions = new List<string>(state.WaveformOptions);
            for (var i = 0; i < _waveNoiseButtons.Length; i++)
            {
                _waveNoiseButtons[i].Visible = i < _waveformOptions.Count;
                if (i < _waveformOptions.Count)
                {
                    _waveNoiseButtons[i].Text = $"{i}: {_waveformOptions[i]}";
                    _waveNoiseButtons[i].Pressed = false;
                }
            }

            return;
        }

        WaveformPanel.Visible = true;
        HintLabel.Text = Loc.GetString("rat-research-minigame-waveform-hint");
        if (!_waveformPopulated)
            PopulateWaveformList(state.WaveformOptions, state.WaveformNoiseIndices);
    }

    private void UpdateCipher(RatResearchMinigameBuiState state)
    {
        if (state.PuzzleStage == 0)
        {
            CipherShiftPanel.Visible = true;
            HintLabel.Text = Loc.GetString("rat-research-minigame-cipher-shift-hint");
            for (var i = 0; i < _cipherShiftButtons.Length; i++)
            {
                if (i < state.CipherShiftOptions.Count)
                {
                    _cipherShiftValues[i] = state.CipherShiftOptions[i];
                    _cipherShiftButtons[i].Visible = true;
                    _cipherShiftButtons[i].Text = Loc.GetString("rat-research-minigame-cipher-shift-option",
                        ("shift", state.CipherShiftOptions[i]));
                }
                else
                {
                    _cipherShiftButtons[i].Visible = false;
                }
            }

            return;
        }

        CipherPanel.Visible = true;
        HintLabel.Text = Loc.GetString("rat-research-minigame-cipher-hint", ("shift", state.CipherShift));
        CipherPromptLabel.Text = Loc.GetString("rat-research-minigame-cipher-prompt");
        CipherTextLabel.Text = state.CipherText;
        UpdateCipherOptions(state.CipherOptions);
    }

    private void UpdateWire(RatResearchMinigameBuiState state)
    {
        if (state.PuzzleStage == 0)
        {
            WirePortPanel.Visible = true;
            HintLabel.Text = Loc.GetString("rat-research-minigame-wire-port-hint");
            return;
        }

        WirePanel.Visible = true;
        HintLabel.Text = Loc.GetString("rat-research-minigame-wire-hint");
        if (!_wireBuilt)
            BuildWireRows();
    }

    private void UpdateBitRepair(RatResearchMinigameBuiState state)
    {
        if (state.PuzzleStage == 0)
        {
            BitCountPanel.Visible = true;
            HintLabel.Text = Loc.GetString("rat-research-minigame-bitrepair-count-hint");
            BitMaskPreviewLabel.Text = Loc.GetString("rat-research-minigame-bitrepair-mask",
                ("value", ToBinaryString(state.BitMask)));
            return;
        }

        BitRepairPanel.Visible = true;
        HintLabel.Text = Loc.GetString("rat-research-minigame-bitrepair-hint");
        if (!_bitBuilt || _bitMask != state.BitMask)
        {
            _bitMask = state.BitMask;
            BuildBitButtons(state.BitMask);
        }

        BitMaskLabel.Text = Loc.GetString("rat-research-minigame-bitrepair-mask",
            ("value", ToBinaryString(state.BitMask)));
        BitCurrentLabel.Text = Loc.GetString("rat-research-minigame-bitrepair-current",
            ("value", ToBinaryString(RatPuzzleUiHelper.ComputeBitMask(_bitButtons))));
    }

    private int GetTimingPosition() =>
        (int) ((_timing.RealTime.TotalSeconds * 35 + _puzzleSeed) % 100);

    private void HidePuzzlePanels()
    {
        TuneBandPanel.Visible = false;
        TunePanel.Visible = false;
        SequencePanel.Visible = false;
        PhasePanel.Visible = false;
        HarmonicPanel.Visible = false;
        WaveformFilterPanel.Visible = false;
        WaveformPanel.Visible = false;
        CipherShiftPanel.Visible = false;
        CipherPanel.Visible = false;
        TimingPanel.Visible = false;
        WirePortPanel.Visible = false;
        WirePanel.Visible = false;
        BitCountPanel.Visible = false;
        MemoryPanel.Visible = false;
        BitRepairPanel.Visible = false;
    }

    private static string GetStageTitle(RatResearchMinigameBuiState state) =>
        Loc.GetString("rat-research-minigame-stage-title",
            ("game", GetGameName(state.ActiveType)),
            ("current", state.PuzzleStage + 1),
            ("total", state.PuzzleStageCount));

    private void UpdateCipherOptions(List<string> options)
    {
        var buttons = new[] { CipherOption0, CipherOption1, CipherOption2, CipherOption3 };
        for (var i = 0; i < buttons.Length; i++)
        {
            buttons[i].Visible = i < options.Count;
            if (i < options.Count)
                buttons[i].Text = options[i];
        }
    }

    private void BuildWireRows()
    {
        WireRows.RemoveAllChildren();
        _wireSpins.Clear();
        for (var i = 0; i < 4; i++)
        {
            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };
            row.AddChild(new Label
            {
                Text = Loc.GetString("rat-research-minigame-wire-row", ("wire", RatPuzzleUiHelper.WireName(i))),
                MinWidth = 120,
            });
            var spin = new SpinBox { MinSize = new System.Numerics.Vector2(80, 0) };
            spin.IsValid = v => v is >= 0 and <= 3;
            spin.OverrideValue(0);
            _wireSpins.Add(spin);
            row.AddChild(spin);
            WireRows.AddChild(row);
        }

        _wireBuilt = true;
    }

    private void BuildMemoryGrid()
    {
        MemoryGrid.RemoveAllChildren();
        _memoryButtons.Clear();
        for (var i = 0; i < 9; i++)
        {
            var idx = i;
            var btn = new Button { Text = (i + 1).ToString(), MinSize = new System.Numerics.Vector2(52, 44) };
            btn.OnPressed += _ => AddMemoryCell(idx);
            _memoryButtons.Add(btn);
            MemoryGrid.AddChild(btn);
        }

        _memoryBuilt = true;
    }

    private void UpdateMemoryDisplay(List<int> pattern, bool showPattern)
    {
        MemoryPatternDisplay.RemoveAllChildren();
        if (showPattern && _memoryReveal && pattern.Count > 0)
        {
            MemoryStatusLabel.Text = Loc.GetString("rat-research-minigame-memory-memorize");
            foreach (var cell in pattern)
                MemoryPatternDisplay.AddChild(new Label { Text = (cell + 1).ToString(), MinWidth = 28 });

            if (_timing.RealTime.TotalSeconds - _memoryRevealStart < 2.5)
                return;

            _memoryReveal = false;
        }

        MemoryStatusLabel.Text = _lastStage == 0
            ? Loc.GetString("rat-research-minigame-memory-repeat")
            : Loc.GetString("rat-research-minigame-memory-reverse");
    }

    private void PopulateWaveformList(List<string> options, List<int> noise)
    {
        WaveformList.Clear();
        _waveformIndexMap.Clear();
        for (var i = 0; i < options.Count; i++)
        {
            if (noise.Contains(i))
                continue;

            WaveformList.AddItem($"{i}: {options[i]}");
            _waveformIndexMap.Add(i);
        }

        _waveformPopulated = true;
        if (WaveformList.Count > 0)
            WaveformList[0].Selected = true;
    }

    private void BuildBitButtons(int initialMask)
    {
        BitButtonsRow.RemoveAllChildren();
        _bitButtons.Clear();
        for (var i = 0; i < 8; i++)
        {
            var btn = new Button
            {
                Text = i.ToString(),
                ToggleMode = true,
                Pressed = (initialMask & (1 << i)) != 0,
                MinSize = new System.Numerics.Vector2(36, 36),
            };
            btn.OnPressed += _ =>
            {
                BitCurrentLabel.Text = Loc.GetString("rat-research-minigame-bitrepair-current",
                    ("value", ToBinaryString(RatPuzzleUiHelper.ComputeBitMask(_bitButtons))));
            };
            _bitButtons.Add(btn);
            BitButtonsRow.AddChild(btn);
        }

        _bitBuilt = true;
    }

    private void PopulateSequenceTarget(List<int> sequence)
    {
        SequenceTargetDisplay.RemoveAllChildren();
        foreach (var value in sequence)
            SequenceTargetDisplay.AddChild(RatPuzzleUiHelper.MakeColorChip(value));
    }

    private void AddSequenceColor(int color)
    {
        if (_sequenceAnswer.Count >= 4)
            return;

        _sequenceAnswer.Add(color);
        ResetSequenceAnswerDisplay();
    }

    private void ResetSequenceAnswer()
    {
        _sequenceAnswer.Clear();
        ResetSequenceAnswerDisplay();
    }

    private void ResetSequenceAnswerDisplay()
    {
        SequenceAnswerDisplay.RemoveAllChildren();
        foreach (var value in _sequenceAnswer)
            SequenceAnswerDisplay.AddChild(RatPuzzleUiHelper.MakeColorChip(value));
    }

    private void AddMemoryCell(int cell)
    {
        if (_memoryReveal)
            return;

        _memoryAnswer.Add(cell);
        ResetMemoryAnswerDisplay();
    }

    private void ResetMemoryAnswer()
    {
        _memoryAnswer.Clear();
        ResetMemoryAnswerDisplay();
    }

    private void ResetMemoryAnswerDisplay()
    {
        foreach (var btn in _memoryButtons)
            btn.Pressed = false;

        foreach (var idx in _memoryAnswer)
        {
            if (idx >= 0 && idx < _memoryButtons.Count)
                _memoryButtons[idx].Pressed = true;
        }
    }

    private void UpdateTuneLabels()
    {
        var a = (int) DialASlider.Value;
        var b = (int) DialBSlider.Value;
        var c = (int) DialCSlider.Value;
        DialAValue.Text = a.ToString();
        DialBValue.Text = b.ToString();
        DialCValue.Text = c.ToString();
        var avg = (a + b + c) / 3f;
        TuneAverageLabel.Text = Loc.GetString("rat-research-minigame-average", ("value", $"{avg:0.#}"));
        if (TuneModulationLabel.Visible)
        {
            TuneModulationLabel.Text = Loc.GetString("rat-research-minigame-tune-modulation-value",
                ("value", (a * b + c) % 100));
        }
    }

    private void UpdatePhaseLabels()
    {
        var a = (int) PhaseASlider.Value;
        var b = (int) PhaseBSlider.Value;
        PhaseAValue.Text = a.ToString();
        PhaseBValue.Text = b.ToString();
        PhaseSumLabel.Text = Loc.GetString("rat-research-minigame-sum-value", ("sum", a + b))
            + " · Δ=" + Math.Abs(a - b);
    }

    private void UpdateHarmonicLabels()
    {
        var stability = (int) StabilitySlider.Value;
        var severity = 100 - stability;
        StabilityValue.Text = stability.ToString();
        SeverityValue.Text = severity.ToString();
        HarmonicProductLabel.Text = Loc.GetString("rat-research-minigame-product-value",
            ("value", stability * severity));
    }

    private static string GetGameName(RatResearchMinigameType type) => type switch
    {
        RatResearchMinigameType.FrequencyTune => Loc.GetString("rat-research-minigame-tune"),
        RatResearchMinigameType.SequenceMatch => Loc.GetString("rat-research-minigame-sequence"),
        RatResearchMinigameType.PhaseLock => Loc.GetString("rat-research-minigame-phase"),
        RatResearchMinigameType.HarmonicBalance => Loc.GetString("rat-research-minigame-harmonic"),
        RatResearchMinigameType.WaveformPick => Loc.GetString("rat-research-minigame-waveform"),
        RatResearchMinigameType.CipherDecrypt => Loc.GetString("rat-research-minigame-cipher"),
        RatResearchMinigameType.TimingPulse => Loc.GetString("rat-research-minigame-timing"),
        RatResearchMinigameType.WireRouting => Loc.GetString("rat-research-minigame-wire"),
        RatResearchMinigameType.MemoryGrid => Loc.GetString("rat-research-minigame-memory"),
        RatResearchMinigameType.BitRepair => Loc.GetString("rat-research-minigame-bitrepair"),
        _ => string.Empty,
    };

    private static string ToBinaryString(int value)
    {
        if (value == 0)
            return "00000000";

        var chars = new char[8];
        for (var i = 7; i >= 0; i--)
        {
            chars[i] = (value & 1) == 1 ? '1' : '0';
            value >>= 1;
        }
        return new string(chars);
    }
}
