using Content.Client.UserInterface.Controls;

using Content.Shared._Rat.SpaceAnomaly;

using Robust.Client.AutoGenerated;

using Robust.Client.UserInterface.Controls;

using Robust.Client.UserInterface.XAML;

using Robust.Shared.Timing;



namespace Content.Client._Rat.SpaceAnomaly;



[GenerateTypedNameReferences]

public sealed partial class SpaceAnomalyStudyConsoleMenu : FancyWindow

{

    private readonly List<SpinBox> _wireSpins = new();

    private readonly List<Button> _memoryButtons = new();

    private readonly List<int> _memoryAnswer = new();

    private readonly IGameTiming _timing;



    private bool _waveformPopulated;

    private bool _wireBuilt;

    private bool _memoryBuilt;

    private bool _memoryReveal;

    private double _memoryRevealStart;

    private SpaceAnomalyStudyStepKind _lastStep;

    private List<int> _lastMemoryPattern = new();



    public event Action? OnRefresh;

    public event Action<NetEntity>? OnSelect;

    public event Action? OnBeginExpedition;

    public event Action<int, int>? OnSubmitPhaseLock;

    public event Action<int>? OnSubmitCipher;

    public event Action<int>? OnSubmitTiming;

    public event Action<List<int>>? OnSubmitWire;

    public event Action<List<int>>? OnSubmitMemory;

    public event Action<int, int>? OnSubmitHarmonic;

    public event Action<int>? OnSubmitWaveform;



    public SpaceAnomalyStudyConsoleMenu()

    {

        RobustXamlLoader.Load(this);

        _timing = IoCManager.Resolve<IGameTiming>();



        WaveformSpinBox.IsValid = v => v is >= 0 and <= 3;

        WaveformSpinBox.OverrideValue(0);



        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();

        BeginButton.OnPressed += _ => OnBeginExpedition?.Invoke();



        PhaseASlider.OnValueChanged += _ => UpdatePhaseLabels();

        PhaseBSlider.OnValueChanged += _ => UpdatePhaseLabels();

        StabilitySlider.OnValueChanged += _ => UpdateHarmonicLabels();

        TimingSlider.OnValueChanged += _ => TimingValue.Text = ((int) TimingSlider.Value).ToString();



        SubmitPhaseButton.OnPressed += _ => OnSubmitPhaseLock?.Invoke(

            (int) PhaseASlider.Value,

            (int) PhaseBSlider.Value);



        CipherOption0.OnPressed += _ => OnSubmitCipher?.Invoke(0);

        CipherOption1.OnPressed += _ => OnSubmitCipher?.Invoke(1);

        CipherOption2.OnPressed += _ => OnSubmitCipher?.Invoke(2);

        CipherOption3.OnPressed += _ => OnSubmitCipher?.Invoke(3);



        SubmitTimingButton.OnPressed += _ => OnSubmitTiming?.Invoke((int) TimingSlider.Value);



        SubmitWireButton.OnPressed += _ =>

        {

            var mapping = new List<int>();

            foreach (var spin in _wireSpins)

                mapping.Add(spin.Value);

            OnSubmitWire?.Invoke(mapping);

        };



        MemoryResetButton.OnPressed += _ => ResetMemoryAnswer();

        SubmitMemoryButton.OnPressed += _ =>

        {

            if (_memoryAnswer.Count > 0)

                OnSubmitMemory?.Invoke(new List<int>(_memoryAnswer));

        };



        SubmitHarmonicButton.OnPressed += _ =>

        {

            var stability = (int) StabilitySlider.Value;

            OnSubmitHarmonic?.Invoke(stability, 100 - stability);

        };



        WaveformList.OnItemSelected += args =>

        {

            WaveformSpinBox.OverrideValue(args.ItemIndex);

            WaveformList[args.ItemIndex].Selected = true;

        };



        SubmitWaveformButton.OnPressed += _ => OnSubmitWaveform?.Invoke(WaveformSpinBox.Value);



        UpdatePhaseLabels();

        UpdateHarmonicLabels();

        TimingValue.Text = ((int) TimingSlider.Value).ToString();

    }



    public void UpdateState(SpaceAnomalyStudyBuiState state)

    {

        if (_lastStep != state.CurrentStep)

        {

            _waveformPopulated = false;

            WaveformList.Clear();

            _wireBuilt = false;

            _memoryBuilt = false;

            _memoryReveal = true;

            _memoryRevealStart = _timing.RealTime.TotalSeconds;

            _memoryAnswer.Clear();

        }



        _lastStep = state.CurrentStep;



        AnomalyList.RemoveAllChildren();

        foreach (var entry in state.Nearby)

        {

            var studied = entry.Studied ? Loc.GetString("space-anomaly-study-studied") : string.Empty;

            var row = new Button

            {

                Text = $"{entry.Name} · {(int) entry.Distance}m · +{entry.PointReward:N0} {studied}",

                Disabled = entry.Studied || state.CurrentStepIndex >= 0,

                HorizontalExpand = true,

                MinHeight = 32,

            };



            if (state.ActiveTarget == entry.Anomaly)

                row.AddStyleClass("ButtonColorGreen");



            var target = entry.Anomaly;

            row.OnPressed += _ => OnSelect?.Invoke(target);

            AnomalyList.AddChild(row);

        }



        UpdateExpeditionPlan(state);



        var totalSteps = state.ExpeditionPlan.Count;

        var currentStep = state.CurrentStepIndex >= 0 ? state.CurrentStepIndex + 1 : 0;

        StatusLabel.Text = state.CurrentStepIndex >= 0
            ? GetStepDisplayText(state.CurrentStep, state)
            : Loc.GetString("space-anomaly-study-stage-idle");

        StepLabel.Text = totalSteps > 0

            ? Loc.GetString("space-anomaly-study-step", ("current", currentStep), ("total", totalSteps))

            : string.Empty;



        RewardLabel.Text = state.PointReward > 0

            ? Loc.GetString("space-anomaly-study-reward-preview", ("points", state.PointReward))

            : string.Empty;



        BeginButton.Visible = state.CurrentStepIndex < 0;

        BeginButton.Disabled = state.ActiveTarget == null;



        HideStagePanels();



        IdleStageLabel.Visible = state.CurrentStepIndex < 0;



        if (state.CurrentStepIndex < 0)

            return;



        switch (state.CurrentStep)

        {

            case SpaceAnomalyStudyStepKind.RemotePhaseLock:

                PhasePanel.Visible = state.PuzzleActive;

                PhaseHintLabel.Text = Loc.GetString("space-anomaly-study-phase-hint",

                    ("low", state.HintLow), ("high", state.HintHigh));

                PhaseSumLabel.Text = Loc.GetString("space-anomaly-study-sum-target",

                    ("low", state.HintLow), ("high", state.HintHigh));

                break;

            case SpaceAnomalyStudyStepKind.RemoteCipher:

                CipherPanel.Visible = state.PuzzleActive;

                CipherHintLabel.Text = Loc.GetString("space-anomaly-study-cipher-hint", ("shift", state.CipherShift));

                CipherTextLabel.Text = state.CipherText;

                UpdateCipherOptions(state.CipherOptions);

                break;

            case SpaceAnomalyStudyStepKind.RemoteTimingPulse:

                TimingPanel.Visible = state.PuzzleActive;

                TimingHintLabel.Text = Loc.GetString("space-anomaly-study-timing-hint",

                    ("low", state.TimingZoneLow), ("high", state.TimingZoneHigh));

                break;

            case SpaceAnomalyStudyStepKind.RemoteWireRoute:

                WirePanel.Visible = state.PuzzleActive;

                if (!_wireBuilt)

                    BuildWireRows();

                break;

            case SpaceAnomalyStudyStepKind.RemoteMemoryGrid:

                MemoryPanel.Visible = state.PuzzleActive;

                if (!_memoryBuilt)

                    BuildMemoryGrid();

                UpdateMemoryDisplay(state.MemoryPattern);

                break;

            case SpaceAnomalyStudyStepKind.RemoteHarmonic:

                HarmonicPanel.Visible = state.PuzzleActive;

                HarmonicHintLabel.Text = Loc.GetString("space-anomaly-study-harmonic-hint",

                    ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));

                HarmonicProductLabel.Text = Loc.GetString("space-anomaly-study-product-target",

                    ("low", state.HintSecondaryLow), ("high", state.HintSecondaryHigh));

                break;

            case SpaceAnomalyStudyStepKind.RemoteWaveformArchive:

                WaveformPanel.Visible = state.PuzzleActive;

                if (state.PuzzleActive && !_waveformPopulated)

                    PopulateWaveformList(state.WaveformOptions);

                break;

            case SpaceAnomalyStudyStepKind.EvaFieldScan:

                EvaPanel.Visible = true;

                EvaStatusLabel.Text = Loc.GetString("space-anomaly-study-stage-eva-depart");

                EvaHintLabel.Text = Loc.GetString("space-anomaly-study-eva-hint");

                break;

            case SpaceAnomalyStudyStepKind.EvaCloseProbe:

                EvaPanel.Visible = true;

                EvaStatusLabel.Text = Loc.GetString("space-anomaly-study-stage-close-probe");

                EvaHintLabel.Text = Loc.GetString("space-anomaly-study-eva-probe-pending");

                break;

            case SpaceAnomalyStudyStepKind.EvaSpectralScan:

                EvaPanel.Visible = true;

                EvaStatusLabel.Text = Loc.GetString("space-anomaly-study-stage-spectral");

                EvaHintLabel.Text = Loc.GetString("space-anomaly-study-spectral-hint");

                break;

            case SpaceAnomalyStudyStepKind.EvaChemicalInject:

                EvaPanel.Visible = true;

                EvaStatusLabel.Text = Loc.GetString("space-anomaly-study-stage-chemical");

                EvaHintLabel.Text = Loc.GetString("space-anomaly-study-chemical-hint",

                    ("reagent", state.RequiredReagent),

                    ("amount", (int) state.RequiredReagentUnits));

                break;

            case SpaceAnomalyStudyStepKind.EvaStabilizerDeploy:

                EvaPanel.Visible = true;

                EvaStatusLabel.Text = Loc.GetString("space-anomaly-study-stage-stabilizer");

                EvaHintLabel.Text = Loc.GetString("space-anomaly-study-stabilizer-hint");

                break;

        }

    }



    private void UpdateExpeditionPlan(SpaceAnomalyStudyBuiState state)

    {

        ExpeditionPlanList.RemoveAllChildren();



        for (var i = 0; i < state.ExpeditionPlan.Count; i++)

        {

            var step = state.ExpeditionPlan[i];

            var prefix = i == state.CurrentStepIndex ? "▶ " : i < state.CurrentStepIndex ? "✓ " : "  ";

            var label = new Label { Text = prefix + GetStepDisplayText(step, state) };

            ExpeditionPlanList.AddChild(label);

        }

    }



    private void HideStagePanels()

    {

        PhasePanel.Visible = false;

        CipherPanel.Visible = false;

        TimingPanel.Visible = false;

        WirePanel.Visible = false;

        MemoryPanel.Visible = false;

        EvaPanel.Visible = false;

        HarmonicPanel.Visible = false;

        WaveformPanel.Visible = false;

    }



    private void UpdateCipherOptions(List<string> options)

    {

        var buttons = new[] { CipherOption0, CipherOption1, CipherOption2, CipherOption3 };

        for (var i = 0; i < buttons.Length; i++)

        {

            buttons[i].Visible = i < options.Count;

            if (i < options.Count)

                buttons[i].Text = options[i];

        }

    }



    private void BuildWireRows()

    {

        WireRows.RemoveAllChildren();

        _wireSpins.Clear();



        for (var i = 0; i < 4; i++)

        {

            var row = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, SeparationOverride = 8 };

            row.AddChild(new Label

            {

                Text = Loc.GetString("rat-research-minigame-wire-row", ("wire", RatPuzzleUiHelper.WireName(i))),

                MinWidth = 120,

            });



            var spin = new SpinBox { MinSize = new System.Numerics.Vector2(80, 0) };

            spin.IsValid = v => v is >= 0 and <= 3;

            spin.OverrideValue(0);

            _wireSpins.Add(spin);

            row.AddChild(spin);

            WireRows.AddChild(row);

        }



        _wireBuilt = true;

    }



    private void BuildMemoryGrid()

    {

        MemoryGrid.RemoveAllChildren();

        _memoryButtons.Clear();



        for (var i = 0; i < 9; i++)

        {

            var idx = i;

            var btn = new Button { Text = (i + 1).ToString(), MinSize = new System.Numerics.Vector2(52, 44) };

            btn.OnPressed += _ => AddMemoryCell(idx);

            _memoryButtons.Add(btn);

            MemoryGrid.AddChild(btn);

        }



        _memoryBuilt = true;

    }



    private void UpdateMemoryDisplay(List<int> pattern)

    {

        if (!ListsEqual(pattern, _lastMemoryPattern))

        {

            _lastMemoryPattern = new List<int>(pattern);

            _memoryReveal = true;

            _memoryRevealStart = _timing.RealTime.TotalSeconds;

            _memoryAnswer.Clear();

        }



        MemoryPatternDisplay.RemoveAllChildren();



        if (_memoryReveal && pattern.Count > 0)

        {

            MemoryStatusLabel.Text = Loc.GetString("rat-research-minigame-memory-memorize");

            foreach (var cell in pattern)

                MemoryPatternDisplay.AddChild(new Label { Text = (cell + 1).ToString(), MinWidth = 28 });



            if (_timing.RealTime.TotalSeconds - _memoryRevealStart < 2.5)

                return;



            _memoryReveal = false;

        }



        MemoryStatusLabel.Text = Loc.GetString("rat-research-minigame-memory-repeat");

    }



    private static bool ListsEqual(List<int> a, List<int> b)

    {

        if (a.Count != b.Count)

            return false;



        for (var i = 0; i < a.Count; i++)

        {

            if (a[i] != b[i])

                return false;

        }



        return true;

    }



    private void AddMemoryCell(int cell)

    {

        if (!_memoryReveal)

            _memoryAnswer.Add(cell);



        ResetMemoryAnswerDisplay();

    }



    private void ResetMemoryAnswer()

    {

        _memoryAnswer.Clear();

        ResetMemoryAnswerDisplay();

    }



    private void ResetMemoryAnswerDisplay()

    {

        foreach (var btn in _memoryButtons)

            btn.Pressed = false;



        foreach (var idx in _memoryAnswer)

        {

            if (idx >= 0 && idx < _memoryButtons.Count)

                _memoryButtons[idx].Pressed = true;

        }

    }



    private void PopulateWaveformList(List<string> options)

    {

        WaveformList.Clear();

        for (var i = 0; i < options.Count; i++)

            WaveformList.AddItem($"{i}: {options[i]}");



        _waveformPopulated = true;

        if (WaveformList.Count > 0)

            WaveformList[0].Selected = true;

    }



    private void UpdatePhaseLabels()

    {

        var a = (int) PhaseASlider.Value;

        var b = (int) PhaseBSlider.Value;

        PhaseAValue.Text = a.ToString();

        PhaseBValue.Text = b.ToString();

        PhaseSumLabel.Text = Loc.GetString("space-anomaly-study-sum-value", ("sum", a + b));

    }



    private void UpdateHarmonicLabels()

    {

        var stability = (int) StabilitySlider.Value;

        var severity = 100 - stability;

        StabilityValue.Text = stability.ToString();

        SeverityValue.Text = severity.ToString();

        HarmonicProductLabel.Text = Loc.GetString("space-anomaly-study-product-value", ("value", stability * severity));

    }



    private static string GetStepDisplayText(SpaceAnomalyStudyStepKind step, SpaceAnomalyStudyBuiState state) => step switch
    {
        SpaceAnomalyStudyStepKind.EvaChemicalInject => Loc.GetString("space-anomaly-study-stage-chemical",
            ("reagent", state.RequiredReagent), ("amount", (int) state.RequiredReagentUnits)),
        _ => Loc.GetString(GetStepLocale(step)),
    };

    private static string GetStepLocale(SpaceAnomalyStudyStepKind step) => step switch

    {

        SpaceAnomalyStudyStepKind.RemotePhaseLock => "space-anomaly-study-stage-remote",

        SpaceAnomalyStudyStepKind.RemoteCipher => "space-anomaly-study-stage-cipher",

        SpaceAnomalyStudyStepKind.RemoteTimingPulse => "space-anomaly-study-stage-timing",

        SpaceAnomalyStudyStepKind.RemoteWireRoute => "space-anomaly-study-stage-wire",

        SpaceAnomalyStudyStepKind.RemoteMemoryGrid => "space-anomaly-study-stage-memory",

        SpaceAnomalyStudyStepKind.RemoteHarmonic => "space-anomaly-study-stage-harmonic",

        SpaceAnomalyStudyStepKind.EvaFieldScan => "space-anomaly-study-stage-eva-depart",

        SpaceAnomalyStudyStepKind.EvaChemicalInject => "space-anomaly-study-stage-chemical",

        SpaceAnomalyStudyStepKind.EvaCloseProbe => "space-anomaly-study-stage-close-probe",

        SpaceAnomalyStudyStepKind.EvaStabilizerDeploy => "space-anomaly-study-stage-stabilizer",

        SpaceAnomalyStudyStepKind.EvaSpectralScan => "space-anomaly-study-stage-spectral",

        SpaceAnomalyStudyStepKind.RemoteWaveformArchive => "space-anomaly-study-stage-waveform",

        _ => "space-anomaly-study-stage-idle",

    };

}

