using Content.Shared._Ratgore.Factions;
using Content.Shared.Preferences;
using Content.Client.Lobby;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Log;

namespace Content.Client._Ratgore.Factions;

[GenerateTypedNameReferences]
public sealed partial class FactionSelectWindow : DefaultWindow
{
    [Dependency] private readonly IClientPreferencesManager _prefsManager = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;

    private RatFactionSystem? _factionSystem;
    private string? _selectedFaction;
    private List<RatFactionInfo> _availableFactions = new();

    public FactionSelectWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _factionSystem = _entManager.System<RatFactionSystem>();

        ApplyButton.OnPressed += _ => OnApply();
        CancelButton.OnPressed += _ => Close();

        FactionDropdown.OnItemSelected += OnFactionSelected;

        _factionSystem.RequestFactionList();

        _availableFactions = _factionSystem.GetAvailableFactions();

        _factionSystem.OnFactionsChanged += OnFactionsChanged;

        PopulateDropdown();
    }

    private void OnFactionsChanged(List<RatFactionInfo> factions)
    {
        _availableFactions = factions;
        PopulateDropdown();
    }

    private void PopulateDropdown()
    {
        FactionDropdown.Clear();

        FactionDropdown.AddItem(Loc.GetString("rat-faction-selector-none"), 0);

        for (int i = 0; i < _availableFactions.Count; i++)
        {
            var name = _availableFactions[i].IsWhitelisted
                ? $"{_availableFactions[i].Name} [WL]"
                : _availableFactions[i].Name;
            FactionDropdown.AddItem(name, i + 1);
        }

        if (_availableFactions.Count == 0)
        {
            FactionDescription.Text = "Подфракции не созданы или не загружены.\n\nИспользуйте команду:\nfactioncreate <название> <вайтлист:true/false> <описание>\n\nдля создания подфракций.\n\nПодфракция - это дополнительная организация ВНУТРИ основной фракции (БМС, ДСМ и т.д.)";
            FactionDropdown.Disabled = true;
        }
        else
        {
            FactionDescription.Text = "Выберите подфракцию из списка";
            FactionDropdown.Disabled = false;
        }

        var currentProfile = _prefsManager.Preferences?.SelectedCharacter as HumanoidCharacterProfile;
        if (currentProfile != null && !string.IsNullOrEmpty(currentProfile.Subfaction))
        {
            for (int i = 0; i < _availableFactions.Count; i++)
            {
                if (_availableFactions[i].Name == currentProfile.Subfaction)
                {
                    FactionDropdown.SelectId(i + 1);
                    _selectedFaction = _availableFactions[i].Name;
                    FactionDescription.Text = _availableFactions[i].Description;
                    break;
                }
            }
        }
    }

    private void OnFactionSelected(OptionButton.ItemSelectedEventArgs args)
    {
        if (args.Id == 0)
        {
            _selectedFaction = null;
            FactionDescription.Text = "Без подфракции";
            return;
        }

        var idx = args.Id - 1;
        if (idx >= 0 && idx < _availableFactions.Count)
        {
            _selectedFaction = _availableFactions[idx].Name;
            var desc = _availableFactions[idx].Description;
            if (_availableFactions[idx].IsWhitelisted)
            {
                desc += "\n\n[color=yellow]Требуется вайтлист[/color]";
            }

            FactionDescription.Text = desc;

            FactionDescription.InvalidateMeasure();
            FactionDescription.InvalidateArrange();
        }
        else
        {
            Logger.Warning($"Invalid subfaction index: {idx} (total: {_availableFactions.Count})");
        }
    }

    private void OnApply()
    {
        var subfactionName = _selectedFaction ?? "";

        var currentProfile = _prefsManager.Preferences?.SelectedCharacter as HumanoidCharacterProfile;
        if (currentProfile != null)
        {
            var newProfile = currentProfile.WithSubfaction(subfactionName);
            var selectedIndex = _prefsManager.Preferences?.SelectedCharacterIndex ?? 0;
            _prefsManager.UpdateCharacter(newProfile, selectedIndex);

            FactionDescription.Text = string.IsNullOrEmpty(subfactionName)
                ? "Подфракция сброшена."
                : $"Выбрана подфракция: {subfactionName}";
        }

        Close();
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing && _factionSystem != null)
        {
            _factionSystem.OnFactionsChanged -= OnFactionsChanged;
        }
        base.Dispose(disposing);
    }
}
